config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  get "/profile", to: "pages#profile", as: :profile
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :rentals, only: [ :index, :show ]

  get '/rentals/:id/return', to: "rentals#return", as: :rental_return

  resources :games do
    resources :rentals, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/console.rb
class Console < ApplicationRecord
  validates :name, presence: true
  has_many :games
end

app/models/game.rb
class Game < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  belongs_to :user
  belongs_to :console
  has_many :images, dependent: :destroy
  has_many :rentals
  validates :name, :description, :price, presence: true

  def owner
    user
  end
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :game
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user # Quem alugou
  belongs_to :game
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id' # Dono do jogo

  scope :owner_rentals, -> (current_user) { where(owner_id: current_user.id) }

  enum status: [ :waiting_confirmation, :confirmed, :waiting_return, :returned, :canceled ]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # validates :first_name, :last_name, :address, :cpf, :city, presence: true
  has_many :games
  has_many :rentals

  mount_uploader :photo, PhotoUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :store_user_location!, if: :storable_location?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :cpf, :city, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :cpf, :city, :photo])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/ || (params[:controller] =~ /(^games$)/ && params[:action] == 'index')
  end

  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def store_user_location!
    store_location_for(:user, request.fullpath)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  def index
    check_available(Game.all)
    if params[:query].present?
      sql_query = "games.name ILIKE :query OR consoles.name ILIKE :query"
      @games = Game.joins(:console).where(sql_query, query: "%#{params[:query]}%").order(name: :asc)
    else
      @games = Game.where(available: true).order(name: :asc)
    end
  end

  def show
    autorizing
  end

  def new
    @game = Game.new
    @consoles = Console.all
    autorizing
  end

  def create
    @game = Game.new(game_params)
    autorizing
    @game.user = current_user
    if @game.save
      redirect_to game_path(@game)
    else
      render :new
    end
  end

  def edit
    @consoles = Console.all
    autorizing
  end

  def update
    autorizing
    @game.update(game_params)
    redirect_to games_path
  end

  def destroy
    autorizing
    @game.destroy
    redirect_to games_path
  end

  private

  def game_params
    params.require(:game).permit(:name, :description, :price, :console_id, :photo)
  end

  def set_game
    @game = Game.find(params[:id])
  end

  def autorizing
    authorize @game
  end

  def check_available(games)
    today = Date.today
    games.each do |game|
      rentals = Rental.where(game_id: game.id)
      unless game.available || rentals.nil?
        rentals.each do |rental|
          if rental.end_date < today
            game.available = true
            game.save
          end
        end
      end
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @games = Game.all
  end

  def profile
    @user = User.find(current_user.id)
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def index
    @owner_rentals = Rental.owner_rentals(current_user)
    @user_rentals = policy_scope(Rental)
  end

  def show
    set_rental
    authorize @rental
  end

  def new
    @game = Game.find(params[:game_id])
    @rental = Rental.new
    authorize @rental
  end

  def create
    @rental = Rental.new(rental_params)
    @rental.game_id = params[:game_id]
    authorize @rental
    @game = Game.find(params[:game_id])
    @rental.owner_id = @game.user_id
    @rental.user = current_user
    if @rental.save
      @game.available = false
      @game.save
      redirect_to rental_path(@rental)
    else
      render :new
    end
  end

  def return
    @rental = Rental.find(params[:id])
    authorize @rental
    @game = Game.find(@rental.game_id)
    @game.update(available: true)
    redirect_to rentals_path
  end

  private

  def rental_params
    params.require(:rental).permit(:start_date, :end_date)
  end

  def set_rental
    @rental = Rental.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/edit.html.erb
<div class="container">
  <%= simple_form_for(@game) do |f| %>
    <div class="row">
      <div class="col-md-8 col-md-offset-2 new-game-form">
        <h1>Edit Game</h1>

        <div class="form-group">
          <%= f.input :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.input :description, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.input :price, class: 'form-control'  %>
        </div>

        <div class="form-group">
          <%= f.input :console_id, collection: @consoles, label_method: :name, value_method: :id, include_blank: false, class: 'form-control'  %>
        </div>

        <div class="form-group">
          <%= f.input :photo %>
          <%= cl_image_tag(@game.photo, width: 400, height: 300, crop: :fill) %>
          <%= f.input :photo_cache, as: :hidden %>
        </div>

        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/games/index.html.erb
<div class="container games-container">
  <div class="text-center">
    <h1 id="all_games">All Games</h1>
  </div>
  <div class="row text-center">
    <div class="container form_find_game">
      <%= form_tag games_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-inline",
          placeholder: "Find a game"
        %>
        <%= submit_tag "Search" %>
      <% end %>
    </div>
  </div>

  <div class="row index_card">
    <% @games.each do |game| %>
      <%= link_to game_path(game) do %>
        <div class="col-md-4 col-sm-6 col-xs-12">
          <div class="thumbnail">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
               url('<%= cl_image_path game.photo, height: 350, width: 480, crop: :scale %>')">
              <div class="card-name"><%= game.name %></div>
              <div class="card-description">
                <p>R$ <%= "%0.2f" % [game.price] %></p>
                <p><%= game.console.name %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/games/new.html.erb
<div class="container">
  <%= simple_form_for(@game) do |f| %>
    <div class="row">
      <div class="col-md-8 col-md-offset-2 new-game-form">
        <h1>Add a New Game</h1>

        <div class="form-group">
          <%= f.input :name, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.input :description, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.input :price, class: 'form-control'  %>
        </div>

        <div class="form-group">
          <%= f.input :console_id, collection: @consoles, label_method: :name, value_method: :id, include_blank: false, class: 'form-control'  %>
        </div>

        <div class="form-group">
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
        </div>

        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/games/show.html.erb
<div>

</div>





<div>

  <h1 id="show_title"><%= @game.name %></h1>
  <div class="container show">
    <div class="row white">
      <div class="col-md-4">
        <%= cl_image_tag @game.photo, height: 300, width: 400, crop: :fill %>
      </div>
      <div class="col-md-5">
        <p><%= @game.description %></p>
      </div>
      <div class="col-md-5">
        <h3>R$ <%= @game.price %></h3>
        <p><%= @game.console.name %></p>
        <% if policy(@game).show? %>
      <%= link_to new_game_rental_path(@game) do %>
        <button class="btn btn-success">Rent</button>
      <% end %>
    <% end %>

      </div>
      <div class="col-md-2">
        <p>
      <%= link_to games_path do %>
        <button class="btn btn-info">Back to GAMES</button>
      <% end %>
    </p>

      </div>
    </div>
    <% if policy(@game).edit? %>
      <%= link_to edit_game_path(@game) do %>
        <button class="btn btn-primary">Update</button>
      <% end %>
    <% end %>

    <% if policy(@game).destroy? %>
      <%= link_to game_path(@game), method: :delete do %>
        <button class="btn btn-danger">Delete</button>
      <% end %>
    <% end %>
    <br>


    <div style="text-align: center">
      <p>
      <%= link_to games_path do %>
        <button class="btn tn-info"></button>
      <% end %>
    </p>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
   <link rel="shortcut icon" href="http://www.iconj.com/ico/z/2/z2qewht6uq.ico" type="image/x-icon" />
    <title>Vintage Games</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/pages/home.html.erb
<div class= "fundo-verde">
  <div class="container">
    <div class="col-md-10 col-md-offset-1">
      <div class="banner-text text-center banner">
        <h1>ALUGUE JOGOS</h1>
        <p></p>
        <%= link_to games_path do %>
        <button class="btn-home btn-color-home">VAMOS JOGAR</button>
        <% end %>
        <!-- <a class="btn btn-primary btn-lg">Start now</a> -->
        <nav role="navigation"> <a href="#services" class="banner-btn"><img src="images/down-arrow.png" alt=""></a></nav>
      </div>
        <!-- banner text -->
    </div>
  </div>
</div>

  <!-- <div class="container varios-banners"> -->
<div class="text-center">
  <h1>VIDEO GAMES</h1>
  <div class="row">
    <div class="col-md-3 console_card">
      <%= image_tag "2-6.jpg" %>
    </div>
    <div class="col-md-3 console_card">
      <%= image_tag "4-5.jpg" %>
    </div>
    <div class="col-md-3 console_card">
      <%= image_tag "7-3.jpg" %>
    </div>
    <div class="col-md-3 console_card">
      <%= image_tag "6-3.jpg" %>
    </div>
  </div>
</div>

<div class= "text-center">
  <h1>Exemplos de jogos</h1>

  <div class="row">
    <div class="col-md-3 console_card">
      <%= image_tag 'donk.png', onmouseover: "this.src='#{asset_path('donkeygif.gif')}'", onmouseout: "this.src='#{asset_path('donk.png')}'" %>
    </div>

    <div class="col-md-3 console_card">
      <%= image_tag 'mari.png', onmouseover: "this.src='#{asset_path('mariogif2.gif')}'", onmouseout: "this.src='#{asset_path('mari.png')}'" %>
    </div>

    <div class="col-md-3 console_card">
      <%= image_tag 'riú.png', onmouseover: "this.src='#{asset_path('streetgif.gif')}'", onmouseout: "this.src='#{asset_path('riú.png')}'" %>
    </div>

    <div class="col-md-3 console_card">
      <%= image_tag 'sonic.png', onmouseover: "this.src='#{asset_path('sonic.gif')}'", onmouseout: "this.src='#{asset_path('sonic.png')}'" %>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<h1><%= @user.first_name + " " + @user.last_name %></h1>
<%= cl_image_tag @user.photo, height: 300, width: 400, crop: :fill %>
<p>Address: <%= @user.address + " - " + @user.city %></p>
<p>CPF: <%= @user.cpf %></p>
<%= link_to edit_user_registration_path  do %>
  <button class="btn-games btn-new-game">Edit User</button>
<% end %>

app/views/rentals/index.html.erb
<div class="container">
  <h1>My Rentals</h1>
  <table>
    <thead>
      <tr>
        <td>
          <p>User</p>
        </td>
        <td>
          <p>Owner</p>
        </td>
        <td>
          <p>Game</p>
        </td>
        <td>
          <p>Console</p>
        </td>
        <td>
          <p>Returned</p>
        </td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <% @user_rentals.each do |rental| %>
          <tr>
            <td>
              <p><%= User.find(rental.user_id).first_name %></p>
            </td>
            <td>
              <p><%= User.find(rental.owner_id).first_name %></p>
            </td>
            <td>
              <p><%= rental.game.name %></p>
            </td>
            <td>
              <p><%= rental.game.console.name %></p>
            </td>
            <td>
              <p><%= rental.game.available %></p>
            </td>
            <td><%= link_to 'details', rental_path(rental) %></td>
            <td><%= link_to 'return', rental_return_path(rental) %></td>
          </tr>
      <% end %>
    </tbody>
  </table>
  <hr>
  <h1>My Games Rented</h1>
    <table>
    <thead>
      <tr>
        <td>
          <p>User</p>
        </td>
        <td>
          <p>Owner</p>
        </td>
        <td>
          <p>Game</p>
        </td>
        <td>
          <p>Console</p>
        </td>
        <td>
          <p>Returned</p>
        </td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <% @owner_rentals.each do |rental| %>
          <tr>

              <td>
                <p><%= User.find(rental.user_id).first_name %></p>
              </td>
              <td>
                <p><%= User.find(rental.owner_id).first_name %></p>
              </td>
              <td>
                <p><%= rental.game.name %></p>
              </td>
              <td>
                <p><%= rental.game.console.name %></p>
              </td>
              <td>
                <p><%= rental.game.available %></p>
              </td>
              <td><%= link_to 'detalhes', rental_path(rental) %></td>
              <td><%= link_to 'return', rental_return_path(rental) %></td>
          </tr>
      <% end %>
    </tbody>
  </table>
      <div style="text-align: center">
    <p>
      <%= link_to games_path do %>
        <button class="btn btn-info">Back to GAMES</button>
      <% end %>
    </p>
    </div>
</div>

app/views/rentals/new.html.erb
<div>
  <h1 id="show_title">New Rental</h1>
  <h3 id="show_title"><%= @game.name %></h1>
  <div class="container show">
    <div class="row">
      <div class="col-md-4">
        <%= cl_image_tag @game.photo, height: 300, width: 400, crop: :fill %>
      </div>
      <div class="col-md-3">
        <p><%= @game.description %></p>
      </div>
      <div class="col-md-1">
        <p>R$ <%= @game.price %></p>
      </div>
      <div class="col-md-2">
        <p><%= @game.console.name %></p>
      </div>
    </div>
    <div class="row">
      <%= simple_form_for([@game, @rental]) do |f| %>
        <div class="form-group">
          <%= f.input :start_date, class: 'form-control'  %>
        </div>

        <div class="form-group">
          <%= f.input :end_date, class: 'form-control'  %>
        </div>

        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  <%= link_to games_path do %>
    <button class="btn btn-info">Cancel</button>
  <% end %>
  </div>
</div>

app/views/rentals/show.html.erb
<div class="container">
  <h1 id="show_title">Rental</h1>
  <div class="container show">
    <div class="row">
      <div class="col-md-3">
        <p>Owner: <%= User.find(@rental.owner_id).first_name %></p>
      </div>
      <div class="col-md-3">
        <p>User: <%= User.find(@rental.user_id).first_name %></p>
      </div>
      <div class="col-md-3">
        <p><%= @rental.game.name %></p>
      </div>
      <div class="col-md-3">
        <p><%= @rental.game.console.name %></p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3">
        <p>ID: <%= @rental.id %></p>
      </div>
      <div class="col-md-3">
        <p>Start Date: <%= @rental.start_date.to_s %></p>
      </div>
      <div class="col-md-3">
        <p>End Date: <%= @rental.end_date %></p>
      </div>
    </div>
    <%= link_to rentals_path do %>
      <button class="btn btn-info">Back to Rentals</button>
    <% end %>
    <%= link_to games_path do %>
      <button class="btn btn-info">Back to Games</button>
    <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "rodape-logo.png", height: 50 %>
    <% end %>

  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "VINTAGEGMAES.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Games", games_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My Rentals", rentals_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Add Game", new_game_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag User.find(current_user.id).photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to profile_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "Games", games_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>